image: node:latest

pages:
  stage: deploy
  script:
    - mkdir -p public/src/scripts
    - mkdir -p public/src/images
    - mkdir -p public/src/styles
    - mkdir -p public/src/audio
    - cp index.html public/
    - cp -r frontend/src/scripts/* public/src/scripts/
    - cp -r frontend/src/images/* public/src/images/
    - cp -r frontend/src/styles/* public/src/styles/
    - cp -r frontend/src/audio/* public/src/audio/
  artifacts:
    paths:
      - public
  only:
    - main
